FROM alpine:3.10
MAINTAINER "Nick Roy" <roy.nicholas@gmail.com>

ENV ANSIBLE_VERSION=2.4

RUN set -ex && \
    buildDeps="python3-dev build-base libffi-dev openssl-dev" && \
    apk add --no-cache $buildDeps python3 py-pip ca-certificates bash && \
    pip3 install --no-cache-dir --upgrade pip && \
    pip3 install --no-cache-dir ansible==${ANSIBLE_VERSION} && \
    apk del --purge $buildDeps

CMD ["ansible"]
